# Generated by Django 5.0.2 on 2025-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
