# Generated by Django 5.0.2 on 2025-03-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faculty_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
