# Generated by Django 5.0.2 on 2025-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_after_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='event',
            name='checkin_before_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
