# Generated by Django 5.0.2 on 2025-04-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pending_students'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classstudent',
            name='one_student_type_only',
        ),
        migrations.AddConstraint(
            model_name='classstudent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('pending_student__isnull', True), ('student__isnull', False)), models.Q(('pending_student__isnull', False), ('student__isnull', True)), _connector='OR'), name='one_student_type_only'),
        ),
    ]
